project_id = "qadgzwsmiadxwwvsrauz"

[functions.auto-complete-events]
verify_jwt = false

[functions.create-client-auth]
verify_jwt = false

[functions.expire-packages]
verify_jwt = false

[functions.create-invite]
verify_jwt = false

[functions.validate-invite]
verify_jwt = false

[functions.accept-invite]
verify_jwt = false

[functions.signup-coach]
verify_jwt = false

[functions.queue-booking-email]
verify_jwt = false

[functions.client-appointment-actions]
verify_jwt = false

[functions.email-preview]
verify_jwt = false

[functions.email-worker]
verify_jwt = false

[functions.validate-coach-invite]
verify_jwt = false

[functions.compute-client-data]
verify_jwt = false

[functions.client-fsm]
verify_jwt = false

[functions.copilot]
verify_jwt = false

[functions.parse-training-plan]
enabled = true
verify_jwt = true
import_map = "./functions/parse-training-plan/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/parse-training-plan/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/parse-training-plan/*.html" ]
