-- Extend activity_type enum with new event and package tracking types
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'EVENT_CREATED';
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'EVENT_RECURRING_CREATED';
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'EVENT_UPDATED';
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'EVENT_DELETED';
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'PACKAGE_CREATED';
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'PACKAGE_UPDATED';
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'SESSION_STARTED';
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'SESSION_COMPLETED';